
# FROM (CAR_RENTAL_COMPANY_CAR A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY ON A.CAR_ID = B.CAR_ID) C
# JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D ON C.CAR_TYPE = D.CAR_TYPE
# WHERE C.START_DATE


SELECT A.CAR_ID, A.CAR_TYPE, TRUNCATE(A.DAILY_FEE*((100-B.DISCOUNT_RATE)/100)*30, 0) AS FEE
FROM    (SELECT *
        FROM CAR_RENTAL_COMPANY_CAR
        WHERE CAR_ID NOT IN(
                        SELECT CAR_ID
                        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                        WHERE START_DATE LIKE '2022-11%' OR END_DATE LIKE '2022-11%' OR (START_DATE<'2022-11-01' AND END_DATE>'2022-11-30')
        ) AND CAR_TYPE IN ('SUV','세단')) A
        
        JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B ON A.CAR_TYPE = B.CAR_TYPE
WHERE B.DURATION_TYPE REGEXP '^30'
GROUP BY A.CAR_ID, A.CAR_TYPE, FEE
HAVING FEE>=500000 AND FEE<2000000
ORDER BY FEE DESC, A.CAR_TYPE, A.CAR_ID DESC

