-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT(USER_ID)) AS PUCHASED_USERS,
ROUND((COUNT(DISTINCT(USER_ID)) / (SELECT COUNT(DISTINCT(USER_ID))
                 FROM USER_INFO
                 WHERE JOINED LIKE '2021%')),1) AS PUCHASED_RATIO
FROM ONLINE_SALE
WHERE USER_ID IN (SELECT USER_ID
                 FROM USER_INFO
                 WHERE JOINED LIKE '2021%')
GROUP BY YEAR,MONTH
ORDER BY YEAR,MONTH
# SET @MAXCOUNT = SELECT(COUNT(DISTINCT(UESR_ID))) FROM USER_INFO WHERE JOINED LIKE '2021%';

# SELECT YEAR(B.SALES_DATE) AS YEAR, MONTH(B.SALE S_DATE) AS MONTH,COUNT(DISTINCT(B.USER_ID)) AS PUCHASED_USERS, (COUNT(DISTINCT(B.USER_ID)) / @MAXCOUNT) AS PUCHASED_RATIO
# FROM USER_INFO A JOIN ONLINE_SALE B ON A.USER_ID = B.USER_ID
# WHERE A.JOINED LIKE '2021%'
# GROUP BY YEAR,MONTH
# ORDER BY YEAR,MONTH