


SELECT YEAR(SALES_DATE)AS YEAR, MONTH(SALES_DATE)AS MONTH, COUNT(DISTINCT(USER_ID)) AS PUCHASED_USERS, 
ROUND(COUNT(DISTINCT(USER_ID))/
(SELECT COUNT(DISTINCT(USER_ID))
FROM USER_INFO
WHERE JOINED LIKE '2021%'),1)AS PUCHASED_RATIO

FROM USER_INFO NATURAL JOIN ONLINE_SALE
WHERE JOINED LIKE '2021%'
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR, MONTH


