# -- 코드를 입력하세요
# SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
# FROM REST_INFO
# WHERE (FOOD_TYPE,FAVORITES) IN (SELECT FOOD_TYPE,MAX(FAVORITES)
#                    FROM REST_INFO
#                    GROUP BY FOOD_TYPE)
# ORDER BY FOOD_TYPE DESC


WITH TEMP AS
(SELECT *, RANK() OVER(PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS RANKING
FROM REST_INFO)

SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM TEMP
WHERE RANKING =1
ORDER BY FOOD_TYPE DESC