-- 코드를 입력하세요
SELECT A.FLAVOR
FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
     FROM JULY
     GROUP BY FLAVOR) AS B JOIN FIRST_HALF A ON A.FLAVOR = B.FLAVOR
GROUP BY A.FLAVOR
ORDER BY A.TOTAL_ORDER+B.TOTAL_ORDER DESC
LIMIT 3