SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES*PRICE) AS TOTAL_SALES
FROM (BOOK NATURAL JOIN AUTHOR ) NATURAL JOIN BOOK_SALES
WHERE SALES_DATE LIKE '2022-01%'
GROUP BY AUTHOR_ID, AUTHOR_NAME, CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC