# # -- 코드를 입력하세요
# # SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
# # FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# # WHERE CAR_ID IN (SELECT CAR_ID
# #                 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# #                 WHERE MONTH(START_DATE) IN ('08','09','10')
# #                  GROUP BY CAR_ID
# #                  HAVING COUNT(*)>=5)
# #                  AND MONTH(START_DATE) IN ('08','09','10')
# # GROUP BY MONTH(START_DATE), CAR_ID
# # HAVING RECORDS>0
# # ORDER BY MONTH ASC, CAR_ID DESC

SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE CAR_ID IN (SELECT CAR_ID
                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
                WHERE MONTH(START_DATE) IN ('8','9','10')
                GROUP BY CAR_ID
                HAVING COUNT(*)>=5) AND MONTH(START_DATE) IN ('8','9','10')
GROUP BY MONTH,CAR_ID
HAVING RECORDS>0
ORDER BY MONTH, CAR_ID DESC

# SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE CAR_ID IN
#     (SELECT CAR_ID
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#     WHERE START_DATE REGEXP '[2022-]09|08|10'
#     GROUP BY CAR_ID
#     HAVING COUNT(*)>=5) 
    
     
# GROUP BY MONTH,CAR_ID
# HAVING RECORDS>0
# ORDER BY MONTH, CAR_ID DESC