SELECT B.BOOK_ID, A.AUTHOR_NAME, DATE_FORMAT(B.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM AUTHOR A JOIN (
    SELECT BOOK_ID, PUBLISHED_DATE, AUTHOR_ID
    FROM BOOK
    WHERE CATEGORY IN ('경제')
) B ON A.AUTHOR_ID = B.AUTHOR_ID
ORDER BY PUBLISHED_DATE