WITH TEMP AS (
SELECT A.BOARD_ID
FROM USED_GOODS_BOARD A JOIN USED_GOODS_FILE B ON A.BOARD_ID = B.BOARD_ID
GROUP BY A.BOARD_ID
ORDER BY SUM(A.VIEWS) DESC
LIMIT 1
)

SELECT CONCAT('/home/grep/src/',BOARD_ID,'/',FILE_ID,FILE_NAME,FILE_EXT) AS FILE_PATH
FROM USED_GOODS_fILE
WHERE BOARD_ID IN (SELECT BOARD_ID FROM TEMP)
ORDER BY FILE_ID DESC